name: gpx
description: Package for load, manipulate, and save GPS data in GPX format (a light-weight XML data format for the interchange of GPS data - waypoints, routes, and tracks).
version: 0.0.1
homepage: https://github.com/kb0/dart-gpx/
author: Kirill Bychkov <bychkov.kirill.0@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  quiver: '>=2.0.0 <3.0.0'
  xml: ^3.5.0

dev_dependencies:
  test: ^1.6.5
